apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastify-api-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nick0lay/k8s-poc.git  # Replace with your actual Git repository URL
    targetRevision: HEAD
    path: kubernetes/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: fastify-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
