apiVersion: v1                                     # API version for Service
kind: Service                                      # Kind signifies a Service
metadata:
  name: fastify-service                            # Name of the Service (used by Ingress to route traffic)
  labels:
    app: fastify-app                               # Label for the service (not strictly required, but for consistency)
spec:
  type: ClusterIP                                  # Internal only Service (ClusterIP is default; not externally reachable on its own)
  ports:
  - port: 80                                       # Service port (clients (Ingress) will use this port to connect to the service)
    targetPort: 3000                               # Target port on pods that the traffic will be forwarded to (Fastify listens on 3000)
    protocol: TCP                                  # Protocol is TCP for HTTP traffic
  selector:
    app: fastify-app                               # This service routes to any pods with label app=fastify-app (the Fastify Deployment pods)
